<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>12.0</LangVersion>
    <AssemblyName>Wysteria.RiotAlarm</AssemblyName>
    <RootNamespace>Wysteria.RiotAlarm</RootNamespace>
    <EnableDynamicLoading>true</EnableDynamicLoading>
        <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
    <Description>Wysteria Works - Local riot alert for the Warden.</Description>
    <Authors>wisteriae</Authors>
        <Company>wisteriae</Company>
    <Version>1.1.6</Version>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CounterStrikeSharp.API" Version="1.0.350" PrivateAssets="all" />
    <ProjectReference Include="../Wysteria.Core/Wysteria.Core.csproj" />
  </ItemGroup>
</Project>
